### ISSUE TITLE
Tip/ExternalTipper.m#L91-L93

### ISSUE THREAD

**Issue by lowell** [tanin47/tip#1]
https://github.com/tanin47/tip/blob/ff04a89441d841e6f76cbf109de986456ee47b8a/mac-app/Tip/ExternalTipper.m#L91-L93

FYI - You can just use `NSHomeDirectory()` here instead of dropping down into Darwin.

Looks like a fun and useful project; gonna give it a run when I get home. Thanks for sharing it!

**Comment by tanin47** [comment]
Great suggestion. I didn't know about this. Please keep the code improvement coming :)

**Comment by tanin47** [comment]
Fixed #2
