### ISSUE TITLE
The popup show appear around highlighted text rather than mouse position

### ISSUE THREAD

**Issue by madhur** [tanin47/tip#15]
This is especially important if you are not using keyboard shortcuts. The mouse had moved down to click the context menu and the tip appears at the mouse pointer, instead of highlighted text.

**Comment by tanin47** [comment]
@madhur thank you for reporting an issue. I'd like to use the text's position as well.

Unfortunately, we don't have a way to access the text's position. So, we use the mouse position instead.

**Comment by tanin47** [comment]
Actually, let me explore if `NSPasteBoard` contains the position of the selected text. I'll get back to you on this.

If you have any other suggestion, please don't hesitate to let me know.

**Comment by tanin47** [comment]
I don't believe this is possible. We'll have to continue using the mouse position. I'll close this issue.
