### ISSUE TITLE
Idea: Force Touch, 3-finger touch to activate tip

### ISSUE THREAD

**Issue by simonpacis** [tanin47/tip#28]
Hi,

Loving tip! Would it be possible to activate the tooltip by the use of force touch? That would be very useful.

Thanks again!

- Simon

**Comment by tanin47** [comment]
I never use force touch before! But it seems we can map the force touch to emit a certain key combination: https://apple.stackexchange.com/questions/177932/how-do-i-change-the-action-for-force-click-on-a-force-touch-trackpad

I have an in-house app that maps my extra mouse button to Cmd+F3 (for triggering Tip). Let me clean it up and share it with you, so you can use it to map the force touch to the key combination that you want.

**Comment by tanin47** [comment]
@simonpacis I've tested force touch. Force touching is difficult to master. 4-finger touch (or 3-finger touch) seems more intuitive. Would this be something you use?

**Comment by simonpacis** [comment]
Ah, that makes sense! Well, 4-finger or 3-finger would be perfect, because then I'd still retain the original force touch functionality. That would definitely be something I'd use personally.

Thank you, and hope you're well!

**Comment by Bogidon** [comment]
@tanin would absolutely love to try out your 3/4-finger touch app. Love tip a lot, thanks for sharing it! ❤️

**Comment by tanin47** [comment]
Hello all! 

I apologize for the delay. I've been working on this new mouse/trackpad configuration app. I'm planning to sell it... but, for y'all here, it's free forever. I'm thankful for y'all for being interested in Tip! 

Here's the URL: https://gum.co/tqqlk -- it's called Noo.app.

You can download Noo by clicking "subscribe" and use the discount code, `betauser`, to download it for free.

I hope this will help improve the experience of using Tip!

cc @Bogidon @simonpacis @aleksandersumowski @mlask @ihodes @williamchai @brncsk @EwanValentine
