### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by dutzi** [tanin47/tip#31]
Cool idea!

I have a small feature request. Right now when opening the tooltip and hitting Escape, the focus doesn't go back to the previous window. Can this be fixed?

**Comment by tanin47** [comment]
Good catch! 

Currently, the tooltip is destroyed once the tooltip is closed. There must be some trick to lose the focus of the app itself.

I'll take time to figure this out. I hope it's possible.

**Comment by tanin47** [comment]
After exploring it, using `[NSApp hide:nil]` gives the focus back to the previous application.

Ref: https://stackoverflow.com/questions/1738477/deactivate-agent-app-after-fsd-in-cocoa

**Comment by tanin47** [comment]
Thanks again @dutzi. Super appreciated this subtle UX bug.

**Comment by dutzi** [comment]
Cool! Thanks :)

- Eldad

**Comment by tanin47** [comment]
@dutzi we have an RC for 1.2.1, which includes this improvement. I'd love your feedback before I release the stable version https://github.com/tanin47/tip/releases/tag/v1.2.1-rc1

**Comment by dutzi** [comment]
On it!
- Eldad

**Comment by dutzi** [comment]
Works 👍
