### ISSUE TITLE
Adding label to "text" action

### ISSUE THREAD

**Issue by rberenguel** [tanin47/tip#32]
This is a feature request. Currently text action has the text as the visible "label".

The use case would be (for example) having several "text modification actions" and being able to choose among them. For instance, imagine having a `convert_to_milliseconds(input)` and a `convert_to_seconds(input)`. Without a label you would only see the output, which would then be confusing (this is an artificial example).

**Comment by rberenguel** [comment]
Note for @tanin47 Thanks a lot for writing tip. It is very slick, and it is incredibly useful. I already had set up "go to JIRA" stuff for the terminal, had hacked up something with Hammerspoon, but tip makes them less appealing

👏

**Comment by tanin47** [comment]
I hope you meant "more appealing". If it is less appealing, I would love to hear more about why and how.

The label for text makes sense. I'll release with the next version :)

**Comment by rberenguel** [comment]
I meant that my hacks with Hammerspoon and ZSH are now less appealing because tip takes over the same use cases in a much more useful way. My wording may have been confusing, I had similar flows for "go to JIRA" hacked up in other tools, but they are better within tip :)

**Comment by tanin47** [comment]
Thank you for the clarification!

**Comment by tanin47** [comment]
Thanks again @rberenguel. This feature will be released with 1.3.0

**Comment by tanin47** [comment]
@rberenguel we have a RC for 1.2.1, which includes this improvement. I'd love your feedback before I release the stable version https://github.com/tanin47/tip/releases/tag/v1.2.1-rc1
