### ISSUE TITLE
type: execute?

### ISSUE THREAD

**Issue by gingerlime** [tanin47/tip#33]
tip looks awesome. I'm playing around with it and enjoy it. Thank you!

I was wondering if besides `text` and `url`, is it possible to execute any other external script? e.g. bash, run an external program etc? Did I miss anything? otherwise, I think it would really boost its versatility if it's possible.

**Comment by tanin47** [comment]
Great idea. I'll need to think about the design how to communicate the output of the executed command back to you.

My initial thought is that your provider script would return an item below:

```
{
  "type": "execute",
  "label": "Something",
  "value": "some-script.sh some-arg"
}
```

You would need to provide `some-script.sh` in `~/Library/Application\ Scripts/tanin.tip/` due to App Sandbox.

When user selects this option, Tip executes it and get the JSON output in the format (that we already defined) and re-render the tooltip again.

We can definitely support this mechanism.

Taking a step back: what is the specific use case you would like to do with this mechanism?

**Comment by rberenguel** [comment]
I was thinking about this yesterday, and I thought it could just call back the script with an additional command line argument on pressing the action:

Right now (I guess from my own script):

```
provider.script "input data"
```

Instead, the action becomes

```
{
  "type": "execute",
  "label": "Something",
  "value": "does-something-cool",
}
```

And you handle internally the logic in your own script (if argument to execute is passed, run the function named so-and-so):

```
provider.script "input data" --execute does-something-cool
```

**Comment by tanin47** [comment]
Reusing the same script is a neat idea. Actually, I'd remove `--execute`. You can choose your own arguments whatever they are.

**Comment by gingerlime** [comment]
Thanks for looking into this! Sorry for the delay, but just to answer the question about my use-case.

Initially, I wanted to open a url, but using Firefox multi-account containers, and due to some weird limitation, I needed a plugin and then a custom command to launch it... Eventually even this failed (not entirely sure why).

But I was trying to think of other use-cases. I have a couple in mind:

* launching several urls for the same selection. for example: I might want to look-up a user by email on several of our backend systems, so I would typically open 3-4 tabs, each running a query for the email address.
* running an external program with the highlighted text as a param? I can't think of many though

Does it make sense? or maybe I'm over-thinking use-cases here? it's definitely not a huge limitation, and tip is already really useful as-is :)

**Comment by tanin47** [comment]
> launching several urls for the same selection. for example: I might want to look-up a user by email on several of our backend systems, so I would typically open 3-4 tabs, each running a query for the email address.

We can also change the url item to accepts `values` instead of `value`. Then, it'll execute all those URLs when selected.

But supporting `execute` still will enable way more possibility (e.g. launch an application with arguments).

**Comment by jpeeler** [comment]
This is related, but not quite the same thing. I'd like the ability to either pass arguments to the provider.script or to be able call additional external programs from the script.

I was hoping something as simple as this could work:

$ ls ~/Library/Application Scripts/tanin.tip
provider.script* external-script*

provider.script:
```bash
#!/usr/bin/env bash
./external-script resource --json $1
```

I assumed the whole tanin.tip directory would be available in the sandbox, but that does not appear to be the case (looks like the script is executed from /). Perhaps the file is available just at a different path, but I didn't go digging.

**Comment by tanin47** [comment]
Hey @jpeeler, Tip executes `provider.script` in the user's environment with the current directory as `/`. Specifically, we use https://developer.apple.com/documentation/foundation/nsuserunixtask (great design by Apple).

Within `provider.script`, you can access anything because it is run with you as the user.

It should work if you change your script to:

```
#!/usr/bin/env bash
~/Library/Application Scripts/tanin.tip/external-script resource --json $1
```

**Comment by tanin47** [comment]
Hello all,

This is now supported in the 2.0.0-rc1. I'd like you to try it out here: https://github.com/tanin47/tip/releases/tag/v2.0.0-rc1

You can now return the `execute` item like below:

```
{
  "type": "execute",
  "label": "Execute something",
  "args": ["--execute", "some_arg"]
}
```
You can set `args` to suit whatever use case you try to build.

When this item is selected by the user, Tip will execute the provider script with the `args`, as in `./provider.script --execute some_arg`. 

You can code your provider script to handle `--execute` specially and return another set of Tip's items, in which Tip will render another tooltip. If you return`[]` (an empty array), Tip will the tooltip will simply disappear.

Here's one use case I use at work: I compare a lot of numbers from the report and need to plus/minus them to see if they match. Here's how it looks like:

![execute-example (1)](https://user-images.githubusercontent.com/494417/83342064-8bf7e400-a29f-11ea-8c3f-b5ad2476d412.gif)

My provider script store the selected numbers in a temp file.

Please download and try it out for your use case. I'd love your feedback. Thank you!

cc @gingerlime @rberenguel @mwean @hobofan @ambas @gafhyb

**Comment by hobofan** [comment]
[tippytap 0.2.0](https://crates.io/crates/tippytap) with support for creating `execute` tooltips and more general parsing of provider inputs has just been released.

In connection with #29, I noticed that the "--bundle-identifier" is not provided alongside the `execute.args` on a execute tooltip. I'm not sure if that is intended behaviour, @tanin47 ? Sure you could just pass through by specifically putting them into the `execute.args`, but I feel that Tip consistently adding it by default would lead to easier providers and easier to implement provider libraries.

**Comment by tanin47** [comment]
Thank you for pointing it out. Yes, it is by design.

Technically, with `execute`, the currently active app is actually Tip itself because the tooltip is activated after clicking on Tip.

If we want to get the original bundle id, we can forward the bundle id by appending it to `args` when generating the `execute` tip item.

Does the RC version work fine for you? If so, I'll release the stable version. Thank you!

**Comment by hobofan** [comment]
Yup, everything works great! 👍 Also a big fan of the instant closing that came in 1.3. Really feels a lot snappier with that!
