### ISSUE TITLE
tip cannot be triggered in some app (preview, telegram, vscode)

### ISSUE THREAD

**Issue by yujinqiu** [tanin47/tip#38]
Hi there, 
I find that I cannot trigger tip in the pdf document opened by preview with shortcut trigger tooltip not show up. 
But  in  Chrome and  sublime everything work as expected below in Chrome
![image](https://user-images.githubusercontent.com/785405/80194486-03a57400-864d-11ea-9bec-38223260b588.png)

**Comment by rberenguel** [comment]
I can confirm it does not work in Preview (neither from shortcut nor right click->services). Maybe preview is not passing the text selected across? Search in dictionary (native from Mac) doesn't work either.

**Comment by tanin47** [comment]
Yes, unfortunately, this means the app doesn't follow the standard way of doing things. 

For example, if they draw the text manually, then NSServices won't work. But I think this might make sense to file a bug against the apps' creators to get them to fix this. They probably want to "broadcast" to NSServices even if they draw the text manually

**Comment by tanin47** [comment]
For VSCode, please let them know that Tip works with IntelliJ/Sublime. It would be great if Tip works with VSCose as well.

**Comment by tanin47** [comment]
I filed a bug to VSCode here: https://github.com/microsoft/vscode/issues/113252
