### ISSUE TITLE
Tip too large for amount of options

### ISSUE THREAD

**Issue by rberenguel** [tanin47/tip#45]
In RC 1.2.1, with a label for a text action the "tip window size" is too large for the amount of options:
![image](https://user-images.githubusercontent.com/2410938/81534447-54fd7500-9368-11ea-81a8-b8ea360c2534.png)

This also happens with non-text:

![image](https://user-images.githubusercontent.com/2410938/81534487-69417200-9368-11ea-9fb3-253480658f42.png)

This is not the case in the release in the App store:

![image](https://user-images.githubusercontent.com/2410938/81534677-bcb3c000-9368-11ea-9855-b6ce4cc99980.png)

(note that I had edited the text action to always return foo in this situation)

![image](https://user-images.githubusercontent.com/2410938/81534714-cb01dc00-9368-11ea-8c33-6dae0faa3b3f.png)

**Comment by tanin47** [comment]
Hmm... this shouldn't have happened. It seem the height and the width are not computed and applied correctly.

Thank you for reporting a detailed bug.

**Comment by tanin47** [comment]
I can't reproduce this problem. But I suspect that it's due to the fact that we switch to use autolayout + constraint. It just doesn't work as well. I'll switch back to compute the width/height manually. It's more future proof anyway.

**Comment by tanin47** [comment]
v1.3.0-rc1 has been released. https://github.com/tanin47/tip/releases/tag/v1.3.0-rc1

@rberenguel could you try and see if the problem goes away? Thank you!

**Comment by rberenguel** [comment]
This feels unexpected: it still happens

![image](https://user-images.githubusercontent.com/2410938/81781275-2a422680-94f8-11ea-9779-ea5aaa4833c4.png)

**Comment by tanin47** [comment]
Thank you @rberenguel. This is getting tricky, as I can't reproduce the problem. Two more questions:

* Could you select the second item? Does the second item cover the whole gap? (or the gap is outside the second item)?
* If you activate Tip on a shorter text, is the width adjusted to the shorter text? What about longer text? 
* Also, does the height change when activating on different text (shorter, longer, multi-line)?

There must be some difference between my machine and yours that I'm not aware of.

**Comment by rberenguel** [comment]
1. I can't take a screenshot, but selecting the second item marks it in blue across (i.e. selected) but only horizontally, it is not covering the additional lines
2. No, it is always pretty wide, regardless:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/2410938/81842031-a31e9e00-954b-11ea-9781-4eb5cfbefbd4.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/2410938/81842071-b0d42380-954b-11ea-9787-bb89912966bb.png">
3. Height seems stable, regardless
<img width="422" alt="image" src="https://user-images.githubusercontent.com/2410938/81842141-cea18880-954b-11ea-9eaf-a1bfad284de0.png">

I have also confirmed I don't have anything extraneous in the JSON that makes tip fail (no "empty returns" nor "additional JSON fields") 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/2410938/81842559-7fa82300-954c-11ea-9230-8f38e2d89d4c.png">

It still happens after pruning my script so it does just Google Search:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/2410938/81842626-99e20100-954c-11ea-9c10-e33432bfb1e5.png">

Changed to the ruby provider, provided:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2410938/81842670-aebe9480-954c-11ea-89e2-ddfe03c6980a.png">

I wonder what could be causing this, if some screen setting, font size or what.

**Comment by tanin47** [comment]
I notice a few things:

* The tooltip is always of the same size
* The clipped text is interesting. It doesn't remove `'` (single quote), but it replaces some text inside with `...`

**Comment by rberenguel** [comment]
Yes, the ellipis is done by my provider script. Let me know if I can do anything else to help pinpointing the issue.

**Comment by tanin47** [comment]
@rberenguel thank you. I think the main 2 issues are:

1. I don't quite understand auto-layout. Maybe it might be impossible to make auto-layout work with every version of Mac OS X.
2. I can't reproduce problem locally.

I'm still researching if number 1 is common. Manual layouting by computing all components' sizes manually is a decent alternative though. It guarantees to work with every machine.

**Comment by rberenguel** [comment]
If it helps, I'm on `10.15.2 (19C57)`, if you happen to have a more recent version I can just upgrade and forget :D

**Comment by tanin47** [comment]
I'm using `macOS 10.15.4 (19E287)`. `10.15.2` isn't old, and Tip should work it that version correctly.

**Comment by tanin47** [comment]
@rberenguel Thank you for reporting this. I'm a bit new to auto layout on Mac.

I'd like you to try `1.3.0-rc2`. This time we compute the intrinsic size for the table.

https://github.com/tanin47/tip/releases/tag/v1.3.0-rc2

Please let me know if this works. Thank you!

**Comment by rberenguel** [comment]
Thanks! Looks gorgeous now:

<img width="267" alt="image" src="https://user-images.githubusercontent.com/2410938/82140664-b1f99f00-9830-11ea-84a0-fcfca95c2e16.png">

I will close the issue now, thanks a lot

**Comment by tanin47** [comment]
@rberenguel thank you for help test an RC. I really appreciate it!
