### ISSUE TITLE
right-click?

### ISSUE THREAD

**Issue by gingerlime** [tanin47/tip#51]
I <3 tip. It's just so simple but so useful. Thanks again for creating it!

Sorry if this is a dumb question, but is it possible to integrate tip with the right-click menu? or some other option via the mouse only?

I'm usually trying to use the keyboard as much as possible and avoid the mouse, but in tip's case, of course the mouse highlight makes the most sense. The *combination* of mouse *and* keyboard shortcut however makes things a bit less than optimal.

Just curious if there's some ways to make things even a bit faster?

**Comment by gingerlime** [comment]
By the way, I noticed the info on the readme about the app, so I guess I'm interested :)

One more thing I can contribute however. I'm also using the excellent [Karabiner Elements](https://karabiner-elements.pqrs.org/) to customize keyboard shortcuts etc on my Mac.

I created a complex modification rule to map my `scroll lock` key to `cmd-&`, so it's just one click instead of 3 on the keyboard (my `&` is accessible with `shift-7`).

Here's the JSON, in case it's helpful to anyone:

```json
{
  "title": "Map scroll lock to Tip",
  "rules": [
    {
      "description": "Map scroll lock to Cmd+&",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "scroll_lock",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "7",
              "modifiers": [
                "left_command",
                "left_shift"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

To install it, simply:

* save it into a json file.
* copy it to `~/.config/karabiner/assets/complex_modifications`
* add and enable it via the Karabiner UI.
![karabiner-tip](https://user-images.githubusercontent.com/524274/82139978-78bf3000-982c-11ea-8fe0-2844bf959952.gif)

**Comment by tanin47** [comment]
@gingerlime thank you for sharing the config for Karabiner Elements. I think this is great. Tip is a personal productivity tool that should support any personal config. I'll find a place in README (or somewhere) to add all tricks people use to trigger the shortcut.

For the mouse app, I'm still working on it. It's coming soon. Will notify you here when it's ready.

**Comment by gingerlime** [comment]
Cool. Thank you. I thought about a PR for the readme, but it felt a bit crowded ... Maybe it makes sense to use the wiki option of github? Just a suggestion :)

**Comment by tanin47** [comment]
Hey @gingerlime, I finally finished the mouse configuration app.

You can download it from here: https://gumroad.com/l/TQQLK

Please use the discount code, `betauser`, to download it for free forever. Thank you again for trying Tip. I'm really thankful for it.

Even though the screenshot doesn't show, Noo.app does support mapping right click to a shortcut.

Please let me know if you encounter any issue.
