### ISSUE TITLE
Prevent focused app from receiving shortcut

### ISSUE THREAD

**Issue by hobofan** [tanin47/tip#66]
I was wondering if it is possible to prevent the currently focused app from receiving the shortcut that is set for tip. In my case a recent update to Firefox has added some functionality to my chosen shortcut, which breaks my workflow (and there doesn't seem to be a way in Firefox to disable it).

I've chosen a new shortcut for now, which doesn't seem to have any conflicts with any apps I'm using, but it would be annoying if the same thing would happen again in the future. For tip to be truly usable everywhere in the system it would be great if it could take "full control" of the shortcut.

**Comment by tanin47** [comment]
@hobofan unfortunately, Tip's shortcut is set through Mac's keyboard shortcut. It goes through a proper Mac OS layer. 

This has one of the pros where Tip runs in Sandbox, so it respects your privacy and increases security. But one of the cons is what you discovered. We have to come up with a shortcut that is unique.

For my setup, I use Cmd+F3, which seems to be unique enough. Then, I map a mouse button and a trackpad gesture to Cmd+F3 using https://gumroad.com/l/tqqlk (I never press Cmd+F3 manually).

This setup might help you use a more complex shortcut that is unique.

**Comment by hobofan** [comment]
That's more or less what I expected :/ Thanks for the confirmation! :)
